<?
  date_default_timezone_set('UTC');         // Set the default time zone to UTC
 // the next 6 are special for qcn - change when moved to another server
  define("BASEPATH", "/var/www");
  define("BASEURL",  "http://quakecatcher.net");
  define("UPLOADURL","http://quakecatcher.net");
  define("UPLOADPATH","/data/QCN");
  define("GMTPATH",  "/usr/local/gmt");
  define("SACPATH",  "/usr/local/sac");
  define("PHPPATH",  "/usr/local/bin/php");
  define("CSHELL_CMD",  "/bin/csh");
  define("SHELL_CMD",   "/bin/bash");
  define("UNZIP_CMD",  "/usr/bin/unzip");
?>
